#!{{ pkgs.fish }}/bin/fish

set -l font "{{ font }}"
set -l size "{{ size }}"

set -l theme_foreground "{{ foreground }}"
set -l theme_background "{{ background }}"
set -l theme_primary "{{ primary }}"

alias hc herbstclient

hc detect_monitors

set -l mod Mod4

# Remove all existing binds.
hc keyunbind -all
hc mouseunbind --all

hc keybind $mod-Shift-Return    spawn alacritty 
hc keybind $mod-Shift-BackSpace close

# Focus clients.
hc keybind $mod-h               focus left
hc keybind $mod-j               focus down
hc keybind $mod-k               focus up
hc keybind $mod-l               focus right

# Moveing clients.
hc keybind $mod-Shift-h         shift left
hc keybind $mod-Shift-j         shift down
hc keybind $mod-Shift-k         shift up
hc keybind $mod-Shift-l         shift right

# Splitting frames.
hc keybind $mod-u               split bottom 0.5
hc keybind $mod-o               split right 0.5
hc keybind $mod-Control-space   split explode

hc keybind $mod-r               remove

# Resizing frames.
set -l resizestep 0.02

hc keybind $mod-Control-h       resize left +$resizestep
hc keybind $mod-Control-j       resize down +$resizestep
hc keybind $mod-Control-k       resize up +$resizestep
hc keybind $mod-Control-l       resize right +$resizestep

# Tags.
hc rename default 0
for i in $(seq 0 9)
    set -l key $(math "($i + 1) % 10")
    hc add $key
    hc keybind $mod-$key       use_index $i
    hc keybind $mod-Shift-$key move_index $i
end

# Cycle through tags.
hc keybind $mod-period          use_index +1 --skip-visible
hc keybind $mod-comma           use_index -1 --skip-visible

# Layouting.
hc keybind $mod-s               floating toggle
hc keybind $mod-f               fullscreen toggle
hc keybind $mod-space \
    or , and . compare tags.focus.curframe_wcount = 2 \
             . cycle_layout +1 vertical horizontal max vertical grid \
       , cycle_layout +1

# Mouse.
hc mousebind $mod-Button1       move
hc mousebind $mod-Button2       zoom
hc mousebind $mod-Button3       resize

# Focus.
hc keybind $mod-BackSpace       cycle_monitor
hc keybind $mod-Tab             cycle_all +1
hc keybind $mod-Shift-Tab       cycle_all -1
hc keybind $mod-c               cycle
hc keybind $mod-i               jumpto urgent

hc set frame_gap 32
hc set window_gap 32
hc set frame_padding -32

hc set frame_border_width 1
hc attr theme.border_width 1

hc attr theme.title_height 16
hc attr theme.title_when multiple_tabs
hc attr theme.title_font "$font:pixelsize=$size"
hc attr theme.title_depth $(math "round($size / 3)")

hc set frame_border_normal_color $theme_background
hc set frame_border_active_color $theme_primary

hc attr theme.normal.color $theme_background
hc attr theme.normal.tab_title_color \#ff0000
hc attr theme.normal.title_color \#ffff00
hc attr theme.active.color $theme_primary
hc attr theme.active.tab_title_color \#0000ff
hc attr theme.active.title_color \#00ffff

~/.fehbg
